import hashlib
import pickle

from coalib.misc.Constants import Constants


def tag_results(tag_name, project_dir, results):
    """
    This method takes a tag provided from the user and saves the results
    dictionary output by coala to a file. That file is uniquely identified by
    the combined hash of the project directory and the provided tag.

    :param tag_name:    Name of tag provided by user.
    :param project_dir: Directory of the project coala is run on.
    :param results:     Results dictionary generated by coala.
    """
    file_name = (project_dir+" "+tag_name).encode()
    file_name = hashlib.sha224(file_name).hexdigest()
    file = open(Constants.TAGS_DIR+"/"+file_name, 'wb+')
    pickle.dump(results, file)
    file.close()
