overrides: coala.yaml

name: coala
contact: coala.analyzer@gmail.com
description: Linting and Fixing Code for All Languages
build_version: 0.12.0.dev99999999999999
current_version: 0.12.0.dev
version: 0.12.0.dev
release: 0.12.0.dev
branch: master
command_line_interface: coala
package_module: coalib
rtd_maintainer: L.S., F.N., M.K.
ci_directory: .misc
docs_dir: docs
docs_source_dir: ./
docs_toc: false
test_py36: true
allow_generic_no_cover: true

entry_points:
  console_scripts:
    - coala = coalib.coala:main
    - coala-ci = coalib.coala_ci:main
    - coala-json = coalib.coala_json:main
    - coala-format = coalib.coala_format:main
    - coala-delete-orig = coalib.coala_delete_orig:main

dependencies:
  - appdirs~=1.4
  - cached-property~=1.4.3
  - cli-helpers~=1.0.2
  - git+https://gitlab.com/coala/coala-utils#egg=coala-utils-0.7.0
  - colorlog>=2.7,<4.0
  - git+https://gitlab.com/jayvdb/package_manager#egg=dependency-management-0.5.0.dev0
  - packaging>=16.8
  - Pygments~=2.1
  - PyPrint~=0.2.6
  - requests~=2.12
  - setuptools>=21.0.0
  - unidiff~=0.5.2

gitignore_extra_rulesets:
  - node

configuration:
  template_dir:
    - .moban.dt/
    - ../coala-mobans/templates/
    - ../coala-mobans/assets/
  configuration: .moban.yaml
  configuration_dir: ../coala-mobans/
targets:
  - .gitignore: core-gitignore.jj2
  - setup.py: core-setup.py.jj2
  - setup.cfg: core-setup.cfg.jj2
  - requirements.txt: requirements.txt.jj2
  - test-requirements.txt: core-test-requirements.txt.jj2
  - tests/conftest.py: conftest.py
  - coalib/VERSION: VERSION.jj2
  - coalib/__main__.py: __main__.py.jj2
  - runtime.txt: runtime.txt
  - netlify.toml: docs/netlify.toml
  - .misc/appveyor.yml: ci/appveyor.yml.jj2
  - .misc/run_with_env.cmd: run_with_env.cmd
