install:
  - if ! pip3 -V ; then wget -O - https://bootstrap.pypa.io/get-pip.py | python3; fi
  - pip3 install -r requirements.txt

env:
  - CI="Rultor"

docker:
  as_root: true
  image: "coala/rultor-python"

merge:
  fast-forward: only
  script:
    - python3 .misc/adjust_version_number.py coalib/VERSION -b `date --utc +%Y%m%d%H%M%S`
    - bash .misc/deploy.pypi.sh

release:
  script: bash .misc/release.sh

decrypt:
  rultor_secrets.sh: "repo/.misc/rultor_secrets.sh.asc"
