install:
  - >
    if ! pip3 -V ; then
      wget -O get-pip.py https://bootstrap.pypa.io/get-pip.py
      python3 get-pip.py
    fi
  - pip3 install -r requirements.txt

docker:
  as_root: true
  image: "coala/rultor-python"

merge:
  fast-forward: only
  script:
    - DATE=`date --utc +%Y%m%d%H%M%S`
    - python3 .ci/adjust_version_number.py bears/VERSION -b "$DATE"
    - bash .misc/deploy.pypi.sh

release:
  script: bash .misc/release.sh

decrypt:
  rultor_secrets.sh: "repo/.misc/rultor_secrets.sh.asc"
