#! /bin/python3

"""
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <http://www.gnu.org/licenses/>.
"""
import os
from coalib.misc.StringConstants import StringConstants
from coalib.processes.SectionExecutor import SectionExecutor
from coalib.settings.SectionManager import SectionManager

os.environ["LANG"] = "de_DE"
from coalib.misc.i18n import _


if __name__ == "__main__":
    try:
        sections, all_local_bears, all_global_bears = SectionManager().run()
        for section_name in sections:
            section = sections[section_name]
            global_bears = all_global_bears[section_name]
            local_bears = all_local_bears[section_name]

            SectionExecutor(section=section, global_bear_list=global_bears, local_bear_list=local_bears).run()
    except KeyboardInterrupt:
        print(_("Program terminated by user."))
    except SystemExit:
        pass
    except:
        print(_("An unknown error occurred.") + " " + StringConstants.THIS_IS_A_BUG)
