#! /bin/python3

"""
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

from codeclib.fillib.util.settings import Settings
from codeclib.internal import FilterManager

if __name__ == "__main__":
    try:
        # Parse settings
        settings = Settings()
        # Get filters
        manager = FilterManager.FilterManager(settings)
        settings.ensure_settings_available(manager.get_needed_keys())
        settings.save_if_necessary()
        manager.run_processes()
        # were finished!
    except KeyboardInterrupt:
        print("\nTerminated by user.");
